import React, { Component } from 'react';
import brave from "../brave.png"
class AboutBody extends Component {
  
    render() { 
        return (
            <React.Fragment>
                 <div className="hide-on-med-and-down" style={{width:"100%",height:"500px"}}></div>
                <div className="hide-on-large-only" style={{width:"100%",height:"200px"}}></div>
                <div className="container-flued" style={{display:"flex",justifyContent:"center",alignContent:"center"}}>
                    <div  className="row">
                        <div className="col l6 s12">
                            <h3 className="center-align">ABOUT</h3>
                            <h5 className="center-align">Team Braveharted</h5>
                            <p className="flow-text center-align"><strong><em>Braveharted </em></strong>is a team name generated by some inteligent teenagers in RCCG HGA. THe name <strong><em>Braveharted </em></strong> is derived from the word Brave which means " Strong in the face of fear" another word to dicribe it is "COURAGEOUS, RESILIENT " etc. We came up with a slogan saying <strong> <en>Boldest Of Them All</en></strong>. Feel free to dive into are wold of bravery</p>
                        </div>
                        <div  className="col l4 offset-6 s12">
                            <img className="center-align" width="100%" src={brave}></img>
                        </div>
                        
    
                    </div>
                    
    
                </div>
                <div className="hide-on-med-and-down" style={{width:"100%",height:"200px"}}></div>
            </React.Fragment>
        )
    }
}
 
export default AboutBody;